/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Plate = {
  _type: "plate";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type ContentSection = {
  _type: "contentSection";
  heading?: string;
  body?: string;
};

export type Metric = {
  _type: "metric";
  value?: string;
  label?: string;
};

export type LinkItem = {
  _type: "linkItem";
  label?: string;
  href?: string;
};

export type DitherStudy = {
  _id: string;
  _type: "ditherStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  work?: string;
  credit?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type KivItem = {
  _id: string;
  _type: "kivItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tag?: string;
  desc?: string;
  order?: number;
  status?: "Parked" | "Researching" | "Sketching" | "Prototyping" | "Next up";
  premise?: string;
  why?: string;
  notes?: Array<string>;
  openQuestions?: Array<string>;
  stack?: Array<string>;
  sections?: Array<
    {
      _key: string;
    } & ContentSection
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tag?: string;
  desc?: string;
  year?: string;
  order?: number;
  status?: "Live" | "In development" | "Shipped" | "Prototype" | "Archived";
  role?: string;
  timeline?: string;
  stack?: Array<string>;
  href?: string;
  links?: Array<
    {
      _key: string;
    } & LinkItem
  >;
  overview?: string;
  problem?: string;
  approach?: string;
  outcome?: string;
  metrics?: Array<
    {
      _key: string;
    } & Metric
  >;
  sections?: Array<
    {
      _key: string;
    } & ContentSection
  >;
  cover?: Plate;
  gallery?: Array<
    {
      _key: string;
    } & Plate
  >;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  roles?: Array<string>;
  tagline?: string;
  about?: string;
  email?: string;
  location?: string;
  stack?: Array<string>;
  socials?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Plate
  | ContentSection
  | Metric
  | LinkItem
  | DitherStudy
  | SanityImageCrop
  | SanityImageHotspot
  | KivItem
  | Slug
  | Project
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: PROFILE_QUERY
// Query: *[_type == "profile"][0]{    name, role, roles, tagline, about, email, location,    socials[]{ label, href },    stack  }
export type PROFILE_QUERY_RESULT = {
  name: string | null;
  role: string | null;
  roles: Array<string> | null;
  tagline: string | null;
  about: string | null;
  email: string | null;
  location: string | null;
  socials: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  stack: Array<string> | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc, year desc){    _id, tag, title, desc, year, href, status,    "slug": slug.current  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  tag: string | null;
  title: string | null;
  desc: string | null;
  year: string | null;
  href: string | null;
  status:
    "Archived" | "In development" | "Live" | "Prototype" | "Shipped" | null;
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PROJECT_INDEX_QUERY
// Query: *[_type == "project"] | order(order asc, year desc){    _id, title, tag, "slug": slug.current  }
export type PROJECT_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  tag: string | null;
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PROJECT_DETAIL_QUERY
// Query: *[_type == "project" && _id == $id][0]{    _id, title, tag, desc, year, href, status, role, timeline, stack,    overview, problem, approach, outcome,    "slug": slug.current,    links[]{ label, href },    metrics[]{ value, label },    sections[]{ heading, body },    cover{      alt, caption,      "url": asset->url,      "lqip": asset->metadata.lqip,      "aspect": asset->metadata.dimensions.aspectRatio    },    gallery[]{      alt, caption,      "url": asset->url,      "lqip": asset->metadata.lqip,      "aspect": asset->metadata.dimensions.aspectRatio    }  }
export type PROJECT_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string | null;
  tag: string | null;
  desc: string | null;
  year: string | null;
  href: string | null;
  status:
    "Archived" | "In development" | "Live" | "Prototype" | "Shipped" | null;
  role: string | null;
  timeline: string | null;
  stack: Array<string> | null;
  overview: string | null;
  problem: string | null;
  approach: string | null;
  outcome: string | null;
  slug: string | null;
  links: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  metrics: Array<{
    value: string | null;
    label: string | null;
  }> | null;
  sections: Array<{
    heading: string | null;
    body: string | null;
  }> | null;
  cover: {
    alt: string | null;
    caption: string | null;
    url: string | null;
    lqip: string | null;
    aspect: number | null;
  } | null;
  gallery: Array<{
    alt: string | null;
    caption: string | null;
    url: string | null;
    lqip: string | null;
    aspect: number | null;
  }> | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: KIV_QUERY
// Query: *[_type == "kivItem"] | order(order asc){    _id, tag, title, desc, status,    "slug": slug.current  }
export type KIV_QUERY_RESULT = Array<{
  _id: string;
  tag: string | null;
  title: string | null;
  desc: string | null;
  status:
    "Next up" | "Parked" | "Prototyping" | "Researching" | "Sketching" | null;
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: KIV_INDEX_QUERY
// Query: *[_type == "kivItem"] | order(order asc){    _id, title, tag, "slug": slug.current  }
export type KIV_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  tag: string | null;
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: KIV_DETAIL_QUERY
// Query: *[_type == "kivItem" && _id == $id][0]{    _id, title, tag, desc, status, premise, why, notes, openQuestions, stack,    "slug": slug.current,    sections[]{ heading, body }  }
export type KIV_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string | null;
  tag: string | null;
  desc: string | null;
  status:
    "Next up" | "Parked" | "Prototyping" | "Researching" | "Sketching" | null;
  premise: string | null;
  why: string | null;
  notes: Array<string> | null;
  openQuestions: Array<string> | null;
  stack: Array<string> | null;
  slug: string | null;
  sections: Array<{
    heading: string | null;
    body: string | null;
  }> | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: DITHER_QUERY
// Query: *[_type == "ditherStudy"][0]{    work, credit, "imageUrl": image.asset->url  }
export type DITHER_QUERY_RESULT = {
  work: string | null;
  credit: string | null;
  imageUrl: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "profile"][0]{\n    name, role, roles, tagline, about, email, location,\n    socials[]{ label, href },\n    stack\n  }\n': PROFILE_QUERY_RESULT;
    '\n  *[_type == "project"] | order(order asc, year desc){\n    _id, tag, title, desc, year, href, status,\n    "slug": slug.current\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project"] | order(order asc, year desc){\n    _id, title, tag, "slug": slug.current\n  }\n': PROJECT_INDEX_QUERY_RESULT;
    '\n  *[_type == "project" && _id == $id][0]{\n    _id, title, tag, desc, year, href, status, role, timeline, stack,\n    overview, problem, approach, outcome,\n    "slug": slug.current,\n    links[]{ label, href },\n    metrics[]{ value, label },\n    sections[]{ heading, body },\n    cover{\n      alt, caption,\n      "url": asset->url,\n      "lqip": asset->metadata.lqip,\n      "aspect": asset->metadata.dimensions.aspectRatio\n    },\n    gallery[]{\n      alt, caption,\n      "url": asset->url,\n      "lqip": asset->metadata.lqip,\n      "aspect": asset->metadata.dimensions.aspectRatio\n    }\n  }\n': PROJECT_DETAIL_QUERY_RESULT;
    '\n  *[_type == "kivItem"] | order(order asc){\n    _id, tag, title, desc, status,\n    "slug": slug.current\n  }\n': KIV_QUERY_RESULT;
    '\n  *[_type == "kivItem"] | order(order asc){\n    _id, title, tag, "slug": slug.current\n  }\n': KIV_INDEX_QUERY_RESULT;
    '\n  *[_type == "kivItem" && _id == $id][0]{\n    _id, title, tag, desc, status, premise, why, notes, openQuestions, stack,\n    "slug": slug.current,\n    sections[]{ heading, body }\n  }\n': KIV_DETAIL_QUERY_RESULT;
    '\n  *[_type == "ditherStudy"][0]{\n    work, credit, "imageUrl": image.asset->url\n  }\n': DITHER_QUERY_RESULT;
  }
}
