/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type DitherStudy = {
  _id: string;
  _type: "ditherStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  work?: string;
  credit?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type KivItem = {
  _id: string;
  _type: "kivItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tag?: string;
  desc?: string;
  order?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tag?: string;
  desc?: string;
  year?: string;
  href?: string;
  order?: number;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  roles?: Array<string>;
  tagline?: string;
  about?: string;
  email?: string;
  location?: string;
  stack?: Array<string>;
  socials?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | DitherStudy
  | SanityImageCrop
  | SanityImageHotspot
  | KivItem
  | Project
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/queries.ts
// Variable: PROFILE_QUERY
// Query: *[_type == "profile"][0]{    name, role, roles, tagline, about, email, location,    socials[]{ label, href },    stack  }
export type PROFILE_QUERY_RESULT = {
  name: string | null;
  role: string | null;
  roles: Array<string> | null;
  tagline: string | null;
  about: string | null;
  email: string | null;
  location: string | null;
  socials: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  stack: Array<string> | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc, year desc){    _id, tag, title, desc, year, href  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  tag: string | null;
  title: string | null;
  desc: string | null;
  year: string | null;
  href: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: KIV_QUERY
// Query: *[_type == "kivItem"] | order(order asc){    _id, tag, title, desc  }
export type KIV_QUERY_RESULT = Array<{
  _id: string;
  tag: string | null;
  title: string | null;
  desc: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: DITHER_QUERY
// Query: *[_type == "ditherStudy"][0]{    work, credit, "imageUrl": image.asset->url  }
export type DITHER_QUERY_RESULT = {
  work: string | null;
  credit: string | null;
  imageUrl: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "profile"][0]{\n    name, role, roles, tagline, about, email, location,\n    socials[]{ label, href },\n    stack\n  }\n': PROFILE_QUERY_RESULT;
    '\n  *[_type == "project"] | order(order asc, year desc){\n    _id, tag, title, desc, year, href\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "kivItem"] | order(order asc){\n    _id, tag, title, desc\n  }\n': KIV_QUERY_RESULT;
    '\n  *[_type == "ditherStudy"][0]{\n    work, credit, "imageUrl": image.asset->url\n  }\n': DITHER_QUERY_RESULT;
  }
}
