/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Plate = {
  _type: "plate";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type ContentSection = {
  _type: "contentSection";
  heading?: string;
  body?: string;
};

export type LinkItem = {
  _type: "linkItem";
  label?: string;
  href?: string;
};

export type DitherStudy = {
  _id: string;
  _type: "ditherStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  work?: string;
  credit?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Entry = {
  _id: string;
  _type: "entry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  kind?: "note" | "experiment" | "update" | "checkpoint";
  tags?: Array<string>;
  summary?: string;
  body?: string;
  project?: ProjectReference;
  href?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  status?: "Idea" | "In progress" | "Parked" | "Done";
  desc?: string;
  tag?: string;
  year?: string;
  order?: number;
  need?: string;
  requirements?: string;
  judgement?: string;
  decisions?: string;
  change?: string;
  sections?: Array<
    {
      _key: string;
    } & ContentSection
  >;
  standing?: string;
  openQuestions?: Array<string>;
  notes?: Array<string>;
  timeline?: string;
  href?: string;
  links?: Array<
    {
      _key: string;
    } & LinkItem
  >;
  cover?: Plate;
  gallery?: Array<
    {
      _key: string;
    } & Plate
  >;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  statement?: string;
  exploringSince?: string;
  questions?: Array<string>;
  about?: string;
  background?: string;
  email?: string;
  location?: string;
  socials?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Plate
  | ContentSection
  | LinkItem
  | DitherStudy
  | SanityImageCrop
  | SanityImageHotspot
  | ProjectReference
  | Entry
  | Slug
  | Project
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: PROFILE_QUERY
// Query: *[_type == "profile"][0]{    name, statement, exploringSince, questions, about, background, email, location,    socials[]{ label, href }  }
export type PROFILE_QUERY_RESULT = {
  name: string | null;
  statement: string | null;
  exploringSince: string | null;
  questions: Array<string> | null;
  about: string | null;
  background: string | null;
  email: string | null;
  location: string | null;
  socials: Array<{
    label: string | null;
    href: string | null;
  }> | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(    select(status == "Done" => 0, status == "In progress" => 1, status == "Parked" => 2, 3) asc,    order asc,    year desc  ){    _id, tag, title, desc, year, status,    "slug": slug.current  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  tag: string | null;
  title: string | null;
  desc: string | null;
  year: string | null;
  status: "Done" | "Idea" | "In progress" | "Parked" | null;
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PROJECT_INDEX_QUERY
// Query: *[_type == "project"] | order(    select(status == "Done" => 0, status == "In progress" => 1, status == "Parked" => 2, 3) asc,    order asc,    year desc  ){    _id, title, "slug": slug.current  }
export type PROJECT_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: PROJECT_DETAIL_QUERY
// Query: *[_type == "project" && _id == $id][0]{    _id, title, tag, desc, year, href, status, timeline,    need, requirements, judgement, decisions, change,    standing, openQuestions, notes,    "slug": slug.current,    links[]{ label, href },    sections[]{ heading, body },    cover{      alt, caption,      "url": asset->url,      "lqip": asset->metadata.lqip,      "aspect": asset->metadata.dimensions.aspectRatio    },    gallery[]{      alt, caption,      "url": asset->url,      "lqip": asset->metadata.lqip,      "aspect": asset->metadata.dimensions.aspectRatio    },    "entries": *[_type == "entry" && references(^._id)] | order(date desc){      _id, title, date, kind, "slug": slug.current    }  }
export type PROJECT_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string | null;
  tag: string | null;
  desc: string | null;
  year: string | null;
  href: string | null;
  status: "Done" | "Idea" | "In progress" | "Parked" | null;
  timeline: string | null;
  need: string | null;
  requirements: string | null;
  judgement: string | null;
  decisions: string | null;
  change: string | null;
  standing: string | null;
  openQuestions: Array<string> | null;
  notes: Array<string> | null;
  slug: string | null;
  links: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  sections: Array<{
    heading: string | null;
    body: string | null;
  }> | null;
  cover: {
    alt: string | null;
    caption: string | null;
    url: string | null;
    lqip: string | null;
    aspect: number | null;
  } | null;
  gallery: Array<{
    alt: string | null;
    caption: string | null;
    url: string | null;
    lqip: string | null;
    aspect: number | null;
  }> | null;
  entries: Array<{
    _id: string;
    title: string | null;
    date: string | null;
    kind: "checkpoint" | "experiment" | "note" | "update" | null;
    slug: string | null;
  }>;
} | null;

// Source: src/sanity/queries.ts
// Variable: ENTRIES_QUERY
// Query: *[_type == "entry"] | order(date desc, _createdAt desc){    _id, title, date, kind, tags, href,    "summary": coalesce(summary, body),    "slug": slug.current  }
export type ENTRIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  date: string | null;
  kind: "checkpoint" | "experiment" | "note" | "update" | null;
  tags: Array<string> | null;
  href: string | null;
  summary: string | null;
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: LATEST_ENTRIES_QUERY
// Query: *[_type == "entry"] | order(date desc, _createdAt desc)[0...5]{    _id, title, date, kind, tags, href,    "summary": coalesce(summary, body),    "slug": slug.current  }
export type LATEST_ENTRIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  date: string | null;
  kind: "checkpoint" | "experiment" | "note" | "update" | null;
  tags: Array<string> | null;
  href: string | null;
  summary: string | null;
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: ENTRY_INDEX_QUERY
// Query: *[_type == "entry"] | order(date desc, _createdAt desc){    _id, title, "slug": slug.current  }
export type ENTRY_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: ENTRY_DETAIL_QUERY
// Query: *[_type == "entry" && _id == $id][0]{    _id, title, date, kind, tags, summary, body, href,    "slug": slug.current,    project->{ _id, title, status, "slug": slug.current }  }
export type ENTRY_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string | null;
  date: string | null;
  kind: "checkpoint" | "experiment" | "note" | "update" | null;
  tags: Array<string> | null;
  summary: string | null;
  body: string | null;
  href: string | null;
  slug: string | null;
  project: {
    _id: string;
    title: string | null;
    status: "Done" | "Idea" | "In progress" | "Parked" | null;
    slug: string | null;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: DITHER_QUERY
// Query: *[_type == "ditherStudy"][0]{    work, credit, "imageUrl": image.asset->url  }
export type DITHER_QUERY_RESULT = {
  work: string | null;
  credit: string | null;
  imageUrl: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "profile"][0]{\n    name, statement, exploringSince, questions, about, background, email, location,\n    socials[]{ label, href }\n  }\n': PROFILE_QUERY_RESULT;
    '\n  *[_type == "project"] | order(\n    select(status == "Done" => 0, status == "In progress" => 1, status == "Parked" => 2, 3) asc,\n    order asc,\n    year desc\n  ){\n    _id, tag, title, desc, year, status,\n    "slug": slug.current\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project"] | order(\n    select(status == "Done" => 0, status == "In progress" => 1, status == "Parked" => 2, 3) asc,\n    order asc,\n    year desc\n  ){\n    _id, title, "slug": slug.current\n  }\n': PROJECT_INDEX_QUERY_RESULT;
    '\n  *[_type == "project" && _id == $id][0]{\n    _id, title, tag, desc, year, href, status, timeline,\n    need, requirements, judgement, decisions, change,\n    standing, openQuestions, notes,\n    "slug": slug.current,\n    links[]{ label, href },\n    sections[]{ heading, body },\n    cover{\n      alt, caption,\n      "url": asset->url,\n      "lqip": asset->metadata.lqip,\n      "aspect": asset->metadata.dimensions.aspectRatio\n    },\n    gallery[]{\n      alt, caption,\n      "url": asset->url,\n      "lqip": asset->metadata.lqip,\n      "aspect": asset->metadata.dimensions.aspectRatio\n    },\n    "entries": *[_type == "entry" && references(^._id)] | order(date desc){\n      _id, title, date, kind, "slug": slug.current\n    }\n  }\n': PROJECT_DETAIL_QUERY_RESULT;
    '\n  *[_type == "entry"] | order(date desc, _createdAt desc){\n    _id, title, date, kind, tags, href,\n    "summary": coalesce(summary, body),\n    "slug": slug.current\n  }\n': ENTRIES_QUERY_RESULT;
    '\n  *[_type == "entry"] | order(date desc, _createdAt desc)[0...5]{\n    _id, title, date, kind, tags, href,\n    "summary": coalesce(summary, body),\n    "slug": slug.current\n  }\n': LATEST_ENTRIES_QUERY_RESULT;
    '\n  *[_type == "entry"] | order(date desc, _createdAt desc){\n    _id, title, "slug": slug.current\n  }\n': ENTRY_INDEX_QUERY_RESULT;
    '\n  *[_type == "entry" && _id == $id][0]{\n    _id, title, date, kind, tags, summary, body, href,\n    "slug": slug.current,\n    project->{ _id, title, status, "slug": slug.current }\n  }\n': ENTRY_DETAIL_QUERY_RESULT;
    '\n  *[_type == "ditherStudy"][0]{\n    work, credit, "imageUrl": image.asset->url\n  }\n': DITHER_QUERY_RESULT;
  }
}
